[package]
name = "perminal"
version = "0.1.0"
authors = ["André Wagner <andre.nho@gmail.com>"]

[dependencies]
libc = "0.1"
bmp = "0.1"
#ncurses = "5.73"
#freetype-rs = "0.1"
#sdl2 = "0.5"

[dependencies.x11]
features = ["xlib"]

[features]
debug_comm = []
